### ISSUE TITLE
Application中的问题

### ISSUE THREAD

**Issue by didumeiyouxue** [XunMengWinter/PowerfulRetrofit#1]
Hi, 
    你好，我是开发者新人，请教一个问题，为什么Application中返回的是一个临时变量呢？
''' 
public static App get() {
        App inst = sApp;  // <<< 在这里创建临时变量
        if (inst == null) {
            synchronized (App.class) {
                inst = sApp;
                if (inst == null) {
                    inst = new App();
                    sApp = inst;
                }
            }
        }
        return inst;  // <<< 注意这里返回的是临时变量
    }
'''

**Comment by XunMengWinter** [comment]
假设sApp被回收掉了，有两个地方同时调用App.get()，上面的代码可以避免new App()同时执行两次。
